import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Search from "@/components/search/searchEngine";
import logo from '../../../../public/images/SearchLogo.png';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Search Engine Kece!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
